main: "cc.dreamcode.missions.MissionsPlugin"
version: "1.0-InDEV"
name: "Dream-Missions"
description: "Dream-Template plugin written by dreamcode.cc"
website: "https://dreamcode.cc"
author: "eripe14"
api-version: 1.13